name: Deploy Python Bot to VPS

# ржХржЦржи рж░рж╛ржи ржХрж░ржмрзЗ
on:
  push:
    branches:
      - main  # main branch ржП push рж╣рж▓рзЗ ржбрж┐ржкрзНрж▓рзЯ рж╣ржмрзЗ

# ржХрж╛ржЬрзЗрж░ ржзрж╛ржк
jobs:
  deploy:
    name: SSH Deploy Job
    runs-on: ubuntu-latest

    steps:
    - name: ЁЯУж Checkout Repository
      uses: actions/checkout@v3

    - name: ЁЯЪА SSH into VPS and Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}       # рждрзЛржорж╛рж░ VPS IP
        username: ${{ secrets.VPS_USER }}   # VPS ржЗржЙржЬрж╛рж░ (рж╕рж╛ржзрж╛рж░ржгржд root)
        key: ${{ secrets.VPS_KEY }}         # Private SSH Key (id_rsa)
        port: 22
        script: |
          echo "ЁЯУБ Moving to project directory..."
          cd ~/erp

          echo "ЁЯФД Pulling latest code..."
          git pull origin main

          echo "ЁЯРН Activating virtual environment..."
          source venv/bin/activate

          echo "ЁЯУж Installing dependencies..."
          pip install -r requirements.txt

          echo "тЦ╢я╕П Running Python bot..."
          python main.py

          echo "тЬЕ Deployment completed successfully!"
